#!/usr/bin/python
"""
web widget showing recent files in /my/post
"""
from __future__ import division
import os, sys, datetime
from twisted.internet import reactor
from twisted.python import log
from nevow.appserver import NevowSite
from nevow import rend, loaders

top = "/my/post"
recent = 5

class Main(rend.Page):
    docFactory = loaders.xmlstr("""
<ul xmlns:n="http://nevow.com/ns/nevow/0.1"
    n:render="sequence" n:data="files">
  <li n:pattern="item">
    <span class="date" n:render="string" n:data="0"></span>
    <span class="name">
      <a><n:attr name="href">http://bigasterisk.com/post/<n:invisible n:render="string" n:data="1"/></n:attr><n:invisible n:render="string" n:data="1"/></a>
    </span>
    <span class="size">(<n:invisible n:render="string" n:data="2"/>kb)</span>
  </li>
</ul>""")
    def data_files(self, ctx, data):
        files = []
        for filename in os.listdir(top):
            try:
                s = os.stat(os.path.join(top, filename))
                files.append((s.st_mtime, filename, s.st_size))
            except OSError, e:
                print "error", filename, e
        files.sort(reverse=True)
        return [(datetime.datetime.fromtimestamp(t).date().isoformat(),
                 f,
                 s // 1024) for t, f, s in files][:recent]
    
print Main().data_files(0,0)

log.startLogging(sys.stdout)
reactor.listenTCP(9006, NevowSite(Main()))
reactor.run()
