#!bin/python
import sys
from twisted.internet import reactor
from twisted.python import log
from twisted.web import server, resource, static, twcgi

from revyu import recentReviews

class Root(resource.Resource):
    def __init__(self):
        resource.Resource.__init__(self)
        self.children[''] = self

    def render_GET(self, request):
        return recentReviews()

log.startLogging(sys.stdout)
reactor.listenTCP(9007, server.Site(Root()))
reactor.run()
