#!/usr/bin/python
"""
web widget showing recent files in /my/post
"""
from __future__ import division
import os, sys, datetime
from bottle import route, run, template

top = "/my/post"
recent = 8
skipTheseBigDirs = ['/my/post/1956newspaper', '/my/post/dash.copy']

tmpl = '''
<ul n:render="sequence" n:data="files">
  % for date, path, size in files:
  <li>
    <span class="date">{{date}}</span>
    <span class="name">
      <a href="https://bigasterisk.com/post/{{path}}">{{path}}</a>
    </span>
    <span class="size">({{size}}kb)</span>
  </li>
  % end
</ul>
'''

def listFiles(top, sub=''):
    for filename in os.listdir(os.path.join(top, sub)):
        try:
            full = os.path.join(top, sub, filename)
            if os.path.isdir(full) and full not in skipTheseBigDirs:
                for row in listFiles(top, os.path.join(sub, filename)):
                    yield row
            else:
                s = os.stat(full)
                yield (s.st_mtime, os.path.join(sub, filename), s.st_size)
        except OSError, e:
            print "error", filename, e

@route('/')
def index():
    files = list(listFiles(top))   
    files.sort(reverse=True)
    return template(tmpl, files=[(datetime.datetime.fromtimestamp(t).date().isoformat(),
                                  f,
                                  s // 1024) for t, f, s in files][:recent])

run(host='0.0.0.0', port=9006)
    
